### ISSUE TITLE
Does not get the real client ip address when host the application on Cloud like Azure

### ISSUE THREAD

**Issue by BG4WCE** [whois-api-llc/flask-simple-geoip#1]
Since the way the get ip address is `request.remote_addr`, it returns the proxy address instead of the real client address. I suggest to change it as follow .
`if request.environ.get('HTTP_X_FORWARDED_FOR') is None:
        return request.environ['REMOTE_ADDR']
    else:
        return request.environ['HTTP_X_FORWARDED_FOR']
`

**Comment by whoisxmlapi** [comment]
Thank you very much for the notification. We shall check the problem and fix it soon.

**Comment by whoisxmlapi** [comment]
The issue has been fixed.
