### ISSUE TITLE
Explain where to put API keys

### ISSUE THREAD

**Issue by rdegges** [whois-api-llc/flask-simple-geoip#2]
Hey there!

It'd be cool to update the README and put in some information about how to supply the API key. It looks like the library has been changed to take in the key and call it `CONFIG_KEY`, either as a Flask app config variable or an environment variable.

I just got an email from a user who read a blog post I wrote asking about this!

Hope all is well!

**Comment by whoisxmlapi** [comment]
Dear Randall,

thank you for the notification, we will do it.

**Comment by whoisxmlapi** [comment]
Fixed, now it is described in the README. 
Thank you very much again for pointing this out.
